### ISSUE TITLE
Top-level variables are not handled properly in codegen

### ISSUE THREAD

**Issue by thinker227** [Draco-lang/Compiler#131]
Currently, [codegen emits top-level variables as plain variables without proper handling for initialization](https://playground.draco-lang.org/#AXMOzkgsKuAqS8xRqFCwVVBSUuJK5EriSuYCsqy5uNJK85IVchMz8zQ0uaq5FICgoCgzr0SjQtOaq5YLAA==). Initialization should probably moved into the static constructor, and perhaps `val` should be emitted as `readonly`.

**Comment by LPeter1997** [comment]
Closed by #123
