### ISSUE TITLE
Add script that would allow testing Draco.Sdk

### ISSUE THREAD

**Issue by Binto86** [Draco-lang/Compiler#209]

**Comment by alexrp** [comment]
For what it's worth, I've had to solve a number of annoying NuGet/MSBuild problems while doing exactly this for my [Zig SDK](https://github.com/vezel-dev/zig-sdk) project. You might consider looking at the source tree for inspiration. I can also answer any questions you might have.

(Feel free to ignore if my approach doesn't apply to your situation. 🙂)

**Comment by LPeter1997** [comment]
@alexrp The issue came up again recently, so we'll definitely take a look, thanks!
We do have a temporary solution of installing the SDK in a temporary folder with a sample project (it's a PSh script under `scripts` folder) but it has its flaws.
