### ISSUE TITLE
Change the internal parse-tree to be regular classes

### ISSUE THREAD

**Issue by LPeter1997** [Draco-lang/Compiler#52]
They are record-classes currently, which is dangerous, given that they are not written with value-semantics in mind. For that we can provide comparers later, but referential equality should be fine.

We can keep the records if there's a simple way to reintroduce referential equality for all nodes. Otherwise, we'll need classes, which means explicit constructors.

**Comment by thinker227** [comment]
> Otherwise, we'll need classes, which means explicit constructors.

`required` properties from C# 11 are also an option.
